###
GET http://localhost:3000/products

###
# @name createProduct
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Product 1",
    "slug": "product-1",
    "description": "This is product 3",
    "price": 100
}

###

@productId = {{ createProduct.response.body.id }}

###
GET http://localhost:3000/products/{{productId}}

###
PATCH http://localhost:3000/products/{{productId}}

###
DELETE http://localhost:3000/products/{{productId}}
